### ISSUE TITLE
Apply a license to the code?

### ISSUE THREAD

**Issue by apocalyptech** [ZakisM/bl3_save_edit#49]
Hello!  There'd been a bit of a kerfuffle with a fork of FromDarkHell's BL3 editor recently, and I got curious what licenses the other BL3 editors were using.  I noticed that yours is currently unlicensed, which in the U.S. means that it defaults to "no rights reserved" (meaning that technically nobody can make use of the code except on their own personal systems).  It'd probably be a good idea to apply an explicit license to your software, just so it's clear where other users stand.

There's a handy site which can be used to help you make that decision, if you're interested in doing so: https://choosealicense.com/

For my own code, I tend to vacillate between the GPL (the "I care about sharing improvements" option on there) and 3-clause BSD (extraordinarily similar to the MIT license from the "I want it simple and permissive" option on there), but there's a ton of other options, of course!

**Comment by ZakisM** [comment]
Hey, thanks for the info!

That's very useful to know - I just assumed uploading to GitHub meant that people could use the code as they wished.

I have decided to go with the GPL-3.0 License: https://github.com/ZakisM/bl3_save_edit/blob/master/COPYING

**Comment by apocalyptech** [comment]
Cool cool, nice to have that detail sorted.  :)  Cheers!
