### ISSUE TITLE
Wonderlands version planned?

### ISSUE THREAD

**Issue by ensiform** [ZakisM/bl3_save_edit#50]
Only seeing a c# windows GUI one in the community so far in progress, just curious where things stand for cross platform support in editors.

**Comment by ZakisM** [comment]
Hi,

Currently, I don't have any plans within the near future. 

I may come back to this project at some point but for now I am happy for the community to create a forked version for Wonderlands support or I will accept PR's if there is a way to add support without needing a new editor.

Thanks
