### ISSUE TITLE
Guardian rewards capped?

### ISSUE THREAD

**Issue by NotLazy** [ZakisM/bl3_save_edit#57]
Does BL3 cap the guardian rewards? I can't get it to go over +15% on most rewards, and -13.04% or +13.04% on the rest. I've tried many different values, such as 10000, 100000, 60000, etc. and nothing changes, I can't get it to go above.

Do I have any options to raise this limit? I'm on macOS if that matters.

**Comment by xcier** [comment]
yes that is the cap of the game. there is no way everyone is stuck to that max limit it is hard coded into the game.
